name: Frontend CD (deploy UI to AKS)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  ACR_LOGIN_SERVER: week9acr.azurecr.io
  IMAGE_TAG: ${{ github.sha }}
  NS: shop
  AZ_RG: deakinuni
  AKS_NAME: week9aks

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS context
        run: |
          az aks get-credentials --resource-group "$AZ_RG" --name "$AKS_NAME" --overwrite-existing

      - name: Apply frontend manifest
        run: |
          kubectl apply -n "$NS" -f k8s/frontend.yaml

      - name: Set frontend image to exact SHA
        run: |
          kubectl set image deploy/frontend -n "$NS" frontend=${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }}

      - name: Wait for rollout (frontend)
        run: |
          kubectl rollout status deploy/frontend -n "$NS" --timeout=180s

      - name: Show frontend service IP
        run: |
          kubectl get svc frontend -n "$NS" -o wide

      - name: Smoke test UI
        run: |
          set -e
          FRONT=$(kubectl get svc frontend -n "$NS" -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "FRONTEND → http://$FRONT"
          curl -sS -I "http://$FRONT" | head -n1
