# week08/.github/workflows/frontend_ci.yml

name: Frontend CI - Build & Push Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

env:
  # Hardcode to avoid newline/format issues
  ACR_NAME: week8regisry
  ACR_LOGIN_SERVER: week8regisry.azurecr.io

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # (Optional) If you need Azure CLI later, keep this. Otherwise you can remove it.
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build & Push FRONTEND image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ env.ACR_LOGIN_SERVER }}/frontend:latest

      - name: Logout from Azure
        if: always()
        run: az logout
